# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUNGglweYOdo4zI48BK00ViLSVCqY0Pc
"""

!pip install matplotlib numpy

import matplotlib.pyplot as plt
import numpy as np

# Define grid size (7 rows for days, 52 columns for weeks)
rows, cols = 7, 52
grid = np.zeros((rows, cols))

# Simulate blocks dropping
for _ in range(100):  # Simulate 100 contributions
    column = np.random.randint(0, cols)  # Random column for contribution
    for row in range(rows):
        if grid[row, column] == 0:
            grid[row, column] = 1  # Place block
            break

# Display the Tetris-like grid
plt.imshow(grid, cmap="Blues", aspect='auto')
plt.title("Tetris Contribution Game")
plt.axis("off")  # Turn off the axis

# Save the output as an image
plt.savefig("tetris_game.svg", bbox_inches='tight', dpi=300)
plt.show()

from google.colab import files
files.download("tetris_game.svg")