name: Generate Tetris Game

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy

      - name: List files
        run: ls -la  # List files to check if tetris_game.py exists

      - name: Run Tetris Game Script
        run: python tetris_game.py  # Adjust this path if necessary

      - name: Commit and Push SVG
        run: |
          git config --local user.email "kushalvadhar@gmail.com"
          git config --local user.name "KushalVadhar"
          git add tetris_game.svg || echo "No changes to commit"
          git commit -m "Update Tetris Contribution Game" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

